### ISSUE TITLE
Feedback from Peer Review

### ISSUE THREAD

**Issue by WilfHass** [UBC-MDS/pokemon-type-predictor#25]
Revathy Feedback:
- [x] List dependencies in README 
- [x] Reason for choosing specific models (in report and README)

**Comment by vincentho32** [comment]
Ashwin Feedback:
- [x]  add a few important charts/plots in the EDA section of your final report

Tony Feedback:
- [x] add more details in the README.md about the features of the data

Zilong Feedback:
- [x]  prefers the report link in README file is linked to webpage instead of a .md file.   We can create a html file and then use [this](https://htmlpreview.github.io/) to create a html preview.
https://htmlpreview.github.io/?https://github.com/UBC-MDS/pokemon-type-predictor/blob/main/doc/final_report.html

**Comment by carolinetang77** [comment]
Other feedback to consider:
- [x] adding info about hyperparameter tuning in report
- [x] justify preprocessing steps in report (dropping columns, imputation)
- we dropped columns that were unique identifiers
- dropped total because it would mask the effects of other stats
- [x] justify why we chose accuracy as our scoring metric
- because all classes are equally important
- [x] mention that conda is required if not using docker
- [x] add links to license, code of conduct, etc
